#!/bin/sh

#(c) 2025 Chris Delezenski <cmd184psu@gmail.com>
#
# LICENSE: Apache 2.0
#
# This script is used to build multi-purpose file server


# APPNAME := fileserve
# PACKAGE := github.com/cmd184psu/nodetodolist
# REVISION := $(shell git rev-parse --short HEAD)
# BRANCH := $(shell git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n')
# TIME := $(shell date +%d%_b%_y-%I:%M%_\#p)


R=$(git rev-parse --short HEAD)
B=$(git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n')
GV=$(cat ./VERSION)
TS=$(date +%d%_b%_y-%I:%M%p)
export LF="-X main.GitRevision=\"$R\" -X main.GitBranch=\"$B\" -X main.GitVersion=\"$GV\" -X main.GitTimestamp=\"$TS\""


if ! GOOS=linux GOARCH=amd64 CGO_ENABLED=1  go build -ldflags "$LF" -o ./file-server-linux; then
	echo "Failed to build file-server-linux"
	exit 1
fi

sudo install -m 755 file-server-linux /usr/local/bin/
